AgriculturalSupplyStore/Controllers/GioHangController.cs
using AgriculturalSupplyStore.Data;
using AgriculturalSupplyStore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using AgriculturalSupplyStore.Helpers;
using Microsoft.AspNetCore.Authorization;
using System;
using Microsoft.EntityFrameworkCore;

namespace AgriculturalSupplyStore.Controllers
{
    public class GioHangController : Controller
    {
        private readonly AgriculturalsupplystoreDbContext db;

        public GioHangController(AgriculturalsupplystoreDbContext context)
        {
            db = context;
        }

        public List<GioHangHHVM> Cart => HttpContext.Session.Get<List<GioHangHHVM>>(MySetting.CART_KEY) ?? new List<GioHangHHVM>();
        public IActionResult Index()
        {
            return View(Cart);
        }

        public IActionResult AddToCart(string id, int quantity = 1)
        {
            var giohang = Cart;
            var item = giohang.SingleOrDefault(p => p.MaHh == id);
            if (item == null)
            {
                var hangHoa = db.HangHoas
                     .Include(p => p.MaPhanNavigation)
                    .SingleOrDefault(p => p.MaHh == id);
                if (hangHoa == null)
                {
                    TempData["Message"] = $"Không tìm thấy hàng hóa có mã {id}";
                    return Redirect("/404");
                }
                item = new GioHangHHVM
                {
                    MaHh = hangHoa.MaHh,
                    TenHh = hangHoa.TenHh,
                    DonGia = hangHoa.DonGia,
                    TenPhan = hangHoa.MaPhanNavigation.TenPhan,
                    Hinh = hangHoa.Hinh ?? string.Empty,
                    SoLuong = quantity

                };
                giohang.Add(item);
            }
            else
            {
                item.SoLuong += quantity;
            }
            HttpContext.Session.Set(MySetting.CART_KEY, giohang);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveCart(string id)
        {
            var giohang = Cart;
            var item = giohang.SingleOrDefault(p => p.MaHh == id);
            if (item != null)
            {
                giohang.Remove(item);
                HttpContext.Session.Set(MySetting.CART_KEY, giohang);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            if (Cart.Count == 0)
            {
                return Redirect("/");
            }
            return View(Cart);
        }


        [Authorize]
        [HttpPost]
        public IActionResult Checkout(CheckoutVM model)
        {
            if (ModelState.IsValid)
            {
                var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID)?.Value;
                var khachHang = new KhachHang();
                if (model.GiongKhachHang)
                {
                    khachHang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerId);
                }
                var hoadon = new HoaDon
                {
                    MaKh = customerId,
                    HoTen = model.HoTen ?? khachHang?.HoTen,
                    DiaChi = model.DiaChi ?? khachHang?.DiaChi,
                    DienThoai = model.DienThoai ?? khachHang?.DienThoai,
                    NgayDat = DateTime.Now,
                    CachThanhToan = "COD",
                    CachVanChuyen = "Express",
                    MaTrangThai = 0,
                    GhiChu = model.GhiChu                    
                };

                db.Database.BeginTransaction();
                try
                {
                    db.Add(hoadon);
                    db.SaveChanges();

                    var cthds = new List<ChiTietHd>();
                    foreach (var item in Cart)
                    {
                        cthds.Add(new ChiTietHd
                        {
                            MaHd = hoadon.MaHd,
                            SoLuong = item.SoLuong,
                            DonGia = item.DonGia,
                            MaHh = item.MaHh,
                            GiamGia = 0
                        });
                    }
                    db.AddRange(cthds);
                    db.SaveChanges();
                    foreach (var item in Cart)
                    {
                        var hangHoa = db.HangHoas.SingleOrDefault(hh => hh.MaHh == item.MaHh);
                        if (hangHoa != null)
                        {
                            if (hangHoa.SoLuong >= item.SoLuong)
                            {
                                hangHoa.SoLuong -= item.SoLuong; 
                                db.Update(hangHoa);
                            }
                            else
                            {
                                throw new Exception($"Hàng hóa {hangHoa.TenHh} không đủ số lượng trong kho.");
                            }
                        }
                    }

                    db.SaveChanges(); 

                    db.Database.CommitTransaction();
                    HttpContext.Session.Set<List<GioHangHHVM>>(MySetting.CART_KEY, new List<GioHangHHVM>());
                    return View("Success");
                }
                catch (Exception ex)
                {
                    db.Database.RollbackTransaction();
                    ModelState.AddModelError("", "Có lỗi xảy ra khi đặt hàng: " + ex.Message);
                }
            }
            return View(Cart);
        }


        ///AdminHoaDon là trang hiển thị thông tin các đơn hàng
        public IActionResult AdminHoaDon()
        {
            var data = db.HoaDons               
                 .Include(p => p.MaTrangThaiNavigation)     
                .Select(p => new HoaDonVM
            {
                MaHd = p.MaHd,
                MaKh = p.MaKh,
                HoTen = p.HoTen,
                CachThanhToan = p.CachThanhToan,
                CachVanChuyen = p.CachVanChuyen,
                TenTrangThai = p.MaTrangThaiNavigation.TenTrangThai,
                MaTrangThai = p.MaTrangThai,                
            });

            return View(data);
        }

        ///UpdateTrangThai là cập nhập trạng thái đơn hàng
        [HttpPost]
        public JsonResult UpdateTrangThai([FromBody] UpdateTrangThaiVM model)
        {
            var hoaDon = db.HoaDons.FirstOrDefault(hd => hd.MaHd == model.MaHd);
            if (hoaDon != null)
            {
                hoaDon.MaTrangThai = model.MaTrangThai;
                db.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }       


        ///CustomerHoaDon là trang hiển thị thông tin các đơn hàng, tên khách hàng, địa chỉ
        public IActionResult CustomerHoaDon(int mahd)
        {
            var hoaDons = db.HoaDons
               .Include(p => p.MaTrangThaiNavigation)
               .Include(p => p.MaKhNavigation)
               .AsQueryable();
            if (mahd != null)
            {
                hoaDons = hoaDons.Where(p => p.MaHd == mahd);
            }
            var result = hoaDons.Select(p => new HoaDonVM
            {                
                MaHd = p.MaHd,
                MaKh = p.MaKh,
                HoTen = p.HoTen,
                CachThanhToan = p.CachThanhToan,
                CachVanChuyen = p.CachVanChuyen,
                TenTrangThai = p.MaTrangThaiNavigation.TenTrangThai,
                MaTrangThai = p.MaTrangThai,
                NgayDat = p.NgayDat,
                NgayCan = p.NgayCan,
                NgayGiao = p.NgayGiao,
                DiaChi = p.DiaChi,
                PhiVanChuyen = p.PhiVanChuyen,
                MaNv = p.MaNv,
                TenNv = p.MaNvNavigation.HoTen,
                GhiChu = p.GhiChu,
                DienThoai = p.DienThoai,
            });
            return View(result);



        }

        ///CustomerCTHD là trang hiển thị thông tin chi tiết các đơn hàng
        public IActionResult CustomerCTHD()
        {           
            var customerId = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySetting.CLAIM_CUSTOMERID)?.Value;

            if (customerId == null)
            {
                return RedirectToAction("Login", "KhachHang");
            }
            var data = db.ChiTietHds
                .Include(p => p.MaHhNavigation)
                 .ThenInclude(hh => hh.MaPhanNavigation)
                .Include(p => p.MaHdNavigation)
                .Where(p => p.MaHdNavigation.MaKh == customerId)               
                .Select(p => new ChiTietHDVM
                {
                    MaCt = p.MaCt,
                    MaHd = p.MaHd,
                    TenHh = p.MaHhNavigation.TenHh,                
                    DonGia = p.DonGia,
                    SoLuong = p.SoLuong,
                    GiamGia = p.GiamGia,
                    TenPhan = p.MaHhNavigation.MaPhanNavigation.TenPhan,
                    Hinh = p.MaHhNavigation.Hinh,
                    MaTrangThai = p.MaHdNavigation.MaTrangThai
                    
                })
                .ToList();
            if (!data.Any())
            {
                TempData["Message"] = $"Bạn chưa mua đơn hàng nào";
                return Redirect("/404");
            }

            return View(data);
        }

        public IActionResult AdminDetailHoaDon(int? mahd)
        {
            var hoaDons = db.HoaDons
                 .Include(p => p.MaNvNavigation)
                .AsQueryable();
            if (mahd.HasValue)
            {
                hoaDons = hoaDons.Where(p => p.MaHd == mahd.Value);
            }
            var result = hoaDons.Select(p => new HoaDonVM
            {
                MaHd = p.MaHd,
                MaKh = p.MaKh,
                HoTen = p.HoTen,

AgriculturalSupplyStore/Views/GioHang/AdminChiTietHD.cshtml
@model IEnumerable<AgriculturalSupplyStore.ViewModels.ChiTietHDVM>
@{
    ViewData["Title"] = "Chi Tiết Hóa Đơn";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <!-- Container Fluid-->
    <div class="container-fluid" id="container-wrapper">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Chi Tiết Hóa Đơn</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="./">Trang Chủ</a></li>
                <li class="breadcrumb-item">Hóa Đơn</li>
                <li class="breadcrumb-item active" aria-current="page">Chi Tiết Hóa Đơn</li>
            </ol>
        </div>

        <div class="row">
            <div class="col-lg-12 mb-4">
                <!-- Simple Tables -->
                <div class="card">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>
                    <div class="table-responsive" style="">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>Stt</th>
                                    <th class="product-thumbnail">Mã chi tiết </th>
                                    <th class="product-name">Mã hóa đơn</th>
                                    <th class="product-thumbnail">Hình ảnh</th>
                                    <th class="product-name">Tên hàng hóa</th>
                                    <th class="product-price">Giá</th>
                                    <th class="product-quantity">Số lượng</th>
                                    <th class="product-quantity">Giảm giá</th>
                                    <th class="product-total">Thành Tiền</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    int stt = 1;
                                }
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@stt</td>
                                        <td class="product-name">
                                            <h2 class="h5 text-black">@item.MaCt</h2>
                                        </td>
                                        <td class="product-name">
                                            <h2 class="h5 text-black">@item.MaHd</h2>
                                        </td>
                                        <td class="product-thumbnail">
                                            <img src="~/images/hanghoa_images/@item.Hinh" alt="@item.TenHh" style=" max-width: 50px; max-height: 100px;" class="img-fluid rounded shadow-sm">
                                        </td>
                                        <td class="product-name">
                                            <h2 class="h5 text-black">@item.TenHh (@item.MaHh)</h2>
                                        </td>
                                        <td>@item.DonGia.ToString("#,##0.000")₫</td>
                                        <td>
                                            @item.SoLuong
                                        </td>
                                        <td>@item.ThanhTien.ToString("#,##0.000")₫</td>
                                    </tr>
                                    stt++;
                                }
                            </tbody>
                        </table>                  
                    </div>
                    <div class="card-footer"></div>
                </div>
                <div class="row mt-5">
                    <div class="col-md-6 ">
                    </div>
                    <div class="col-md-6 ml-auto  ">
                        <div class="row justify-content-end">
                            <div class="col-md-7">
                                <div class="row">
                                    <div class="col-md-12 text-center border-bottom mb-5">
                                        <h3 class="text-black h4 text-uppercase">Tổng Cộng</h3>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <span class="text-black">Số tiền:</span>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <strong class="text-black">@Model.Sum(p => p.ThanhTien).ToString("#,##0.000")₫</strong>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <span class="text-black">Phí:</span>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <strong class="text-black">Miễn phí vận chuyển trong nước</strong>
                                    </div>
                                </div>
                                <div class="row mb-5">
                                    <div class="col-md-6">
                                        <span class="text-black">Tổng tiền:</span>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <strong class="text-black">@Model.Sum(p => p.ThanhTien).ToString("#,##0.000")₫</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Row-->
    </div>
    <!---Container Fluid-->
</div>

AgriculturalSupplyStore/Views/GioHang/AdminDetailHoaDon.cshtml
@model IEnumerable<AgriculturalSupplyStore.ViewModels.HoaDonVM>
@{
    ViewData["Title"] = "Danh Sách Hóa Đơn";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <!-- Container Fluid-->
    <div class="container-fluid" id="container-wrapper">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Xem Hóa Đơn</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="./">Trang Chủ</a></li>
                <li class="breadcrumb-item">Hóa Đơn</li>
                <li class="breadcrumb-item active" aria-current="page">Xem Hóa Đơn</li>
            </ol>
        </div>

        <div class="row">
            <div class="col-lg-12 mb-4">
                <!-- Simple Tables -->
                <div class="card">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>                                   
                                    <th>Mã hóa đơn</th>                             
                                    <th>Tên khách hàng</th>
                                    <th>Cách thanh toán</th>
                                    <th>Cách vận chuyển</th>
                                    <th>Điện thoại</th>
                                    <th>Địa chỉ</th>
                                    <th>Ghi chú</th>
                                    <th>Trạng thái</th>
                                    <th>Ngày đặt</th>
                                    <th>Ngày cần</th>
                                    <th>Ngày giao</th>                                 
                                    <th>Phí vận chuyển</th>                                                                     
                                    <th>Tác vụ</th>
                                </tr>
                            </thead>
                            <tbody>                               
                                @foreach (var item in Model)
                                {
                                    <tr>                                                                    
                                        <td>@item.MaHd</td>
                                        <td>@item.HoTen (@item.MaKh)</td>
                                        <td>@item.CachThanhToan</td>
                                        <td>@item.CachVanChuyen</td>
                                        <td>@item.DienThoai</td>
                                        <td>@item.DiaChi</td>
                                        <td>@item.GhiChu</td>
                                        <td>@item.TenTrangThai (@item.MaTrangThai)</td>
                                        <td>@item.NgayDat.ToString("dd/MM/yyyy")</td>
                                        <td>@item.NgayCan.ToString("dd/MM/yyyy")</td>
                                        <td>@item.NgayGiao.ToString("dd/MM/yyyy")</td>                                      
                                        <td>@item.PhiVanChuyen</td>                                                              
                                        <td class="d-flex justify-content-center align-items-center w-100 gap-2">
                                            <a asp-action="AdminChiTietHD" asp-route-mahd="@item.MaHd" class="btn btn-sm btn-primary" style="margin-right: 5px;">Xem chi tiết hóa đơn</a>                                           
                                        </td>                                   
                                    </tr>                                    
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
        <!--Row-->
    </div>
    <!---Container Fluid-->
</div>

AgriculturalSupplyStore/Views/GioHang/Checkout.cshtml
@model IEnumerable<AgriculturalSupplyStore.ViewModels.GioHangHHVM>
@{
    ViewData["Title"] = "Thanh Toán";
}
<!-- Start Hero Section -->
<div class="container-fluid bg-breadcrumb">
	<div class="container text-center py-5" style="max-width: 900px;">
		<h4 class="text-white display-4 mb-4 wow fadeInDown " data-wow-delay="0.1s">Trang Đặt Hàng</h4>
		<ol class="breadcrumb d-flex justify-content-center mb-0 wow fadeInDown" data-wow-delay="0.3s">
			<li class="breadcrumb-items_first "><a>Trang Chủ</a></li>
			<li class="breadcrumb-items active text-primary"><a>Giỏ Hàng</a></li>
			<li class="breadcrumb-items active text-primary"><a>Trang Đặt Hàng</a></li>
		</ol>
	</div>
</div>
<!-- End Hero Section -->

<div class="">
	<div class="container">
		<div class="row mb-5">
			<div class="col-md-12">			
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 mb-5 mb-md-0">
				<h2 class="h3 mb-3 text-black d-flex align-items-center justify-content-center">Thông tin giao hàng</h2>
				<form asp-action="Checkout" asp-controller="GioHang">
					<div class="p-3 p-lg-5 border bg-white">
						<div class="form-check my-3">
							<input type="checkbox" name="GiongKhachHang" class="form-check-input" id="GiongKhachHang" value="false" />
							<label class="form-check-label" for="GiongKhachHang">Giống thông tin khách hàng</label>
						</div>
						<div class="form-group row delivery-info">
							<div class="col-md-12">
								<label for="c_companyname" class="text-black">Người nhận hàng</label>
								<input type="text" name="HoTen" class="form-control" id="c_companyname">
							</div>
						</div>

						<div class="form-group row delivery-info">
							<div class="col-md-12">
								<label for="c_address" class="text-black">Địa chỉ nhận hàng <span class="text-danger">*</span></label>
								<input type="text" name="DiaChi" class="form-control" id="c_address"  placeholder="Địa chỉ nhận hàng">
							</div>
						</div>

						<div class="form-group row delivery-info">
							<div class="col-md-6">
								<label for="c_state_country" class="text-black">Điện thoại <span class="text-danger">*</span></label>
								<input type="text" name="DienThoai" class="form-control" id="c_state_country">
							</div>					
							<div class="form-group ">
								<label for="c_order_notes" class="text-black">Ghi chú</label>
								<textarea name="GhiChu" id="c_order_notes" cols="30" rows="5" class="form-control" placeholder="Viết ghi chú cho cửa hàng..."></textarea>
							</div>

						</div>
						<div class="form-group mt-2">
							<button type="submit" class="btn btn-black btn-lg py-3 btn-block" onclick="window.location='thankyou.html'">Đặt Hàng</button>
						</div>
						</div>
				</form>
			</div>
			<div class="col-md-6">			
				<div class="row mb-5">
					<div class="col-md-12" style="padding-top: 0px;">
						<h2 class="h3 mb-3 text-black d-flex align-items-center justify-content-center">Đơn đặt hàng</h2>
						<div class="p-3 p-lg-5 border bg-white">
							<table class="table site-block-order-table mb-5">
								<thead>
								<th>Hình</th>
								<th>Tên Sản Phẩm</th>
								<th>Đơn Giá</th>
								<th>Số Lượng</th>
								<th>Thành Tiền</th>
								</thead>
								<tbody>
									@foreach(var item in Model)
									{
										<tr>
											<td><img src="~/images/hanghoa_images/@item.Hinh" alt="@item.TenHh" width="50px;" /></td>
											<td>@item.TenHh</td>
											<td>@item.DonGia.ToString("#,##0.000")₫</td>
											<td>@item.SoLuong</td>
											<td>@item.ThanhTien.ToString("#,##0.000")₫</td>
										</tr>
									}	
									<tr>
										<th scope="row">
										</th>
										<td class="py-5"></td>
										<td class="py-5"></td>
										<td class="py-5">
											<p class="mb-0 text-dark py-3">Tổng cộng:</p>
										</td>
										<td class="py-5">
											<div class="py-3 border-bottom border-top">
												<p class="mb-0 text-dark">
													@Model.Sum(p => p.ThanhTien).ToString("#,##0.000")₫
												</p>
											</div>
										</td>
									</tr>
								</tbody>
							</table>							
						</div>
					</div>
				</div>

			</div>
		</div>
		<!-- </form> -->
	</div>
</div>
@section Scripts {
	<script>
		$(document).ready(function(){
			$("#GiongKhachHang").change(function(){
				if($(this).prop("checked")){
					$(this).val(true);
					$(".delivery-info").addClass("d-none");
				}else{
					$(this).val(false);
					$(".delivery-info").removeClass("d-none");
				}
			});
		});
	</script>
}									

AgriculturalSupplyStore/Views/GioHang/Index.cshtml
@model IEnumerable<AgriculturalSupplyStore.ViewModels.GioHangHHVM>
@{
    ViewData["Title"] = "Giỏ Hàng";
}
<div class="container-fluid bg-breadcrumb">
    <div class="container text-center py-5" style="max-width: 900px;">
        <h4 class="text-white display-4 mb-4 wow fadeInDown " data-wow-delay="0.1s">Giỏ Hàng Của Bạn</h4>
        <ol class="breadcrumb d-flex justify-content-center mb-0 wow fadeInDown" data-wow-delay="0.3s">
            <li class="breadcrumb-items_first "><a>Trang Chủ</a></li>
            <li class="breadcrumb-items active text-primary"><a>Giỏ Hàng</a></li>
        </ol>
    </div>
</div>
<div class="untree_co-section before-footer-section">
    <div class="container bg-white">
        <div class="row site-blocks-table-1" >
            <form class="col-md-12" method="post">
                <div class="site-blocks-table">
                    <table class="table">                        
                        <tbody class="">
                            @foreach(var item in Model)
                            {
                                <tr>                                    
                                    <td class="product-thumbnail">
                                        <img src="~/images/hanghoa_images/@item.Hinh" alt="@item.TenHh" class="img-fluid" style="width: 100px; height: 100px; object-fit: cover;" />
                                    </td>
                                    <td class="product-name">
                                        <h2 class="h5 text-black">@item.TenHh</h2>
                                    </td>
                                    <td>
                                        <p style="margin: 0px;">Vị trí: @item.TenPhan</p>
                                    </td>
                                    <td>@item.DonGia.ToString("#,##0.000")₫</td>
                                    <td>
                                        <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-outline-black decrease" type="button">&minus;</button>
                                            </div>
                                            <input type="text" class="form-control text-center quantity-amount" value="@item.SoLuong" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                                            <div class="input-group-append">
                                                <button class="btn btn-outline-black increase" type="button">&plus;</button>
                                            </div>
                                        </div>

                                    </td>
                                    <td>@item.ThanhTien.ToString("#,##0.000")₫</td>
                                    <td><a asp-action="RemoveCart" asp-controller="GioHang" asp-route-id="@item.MaHh" class="fa fa-trash "></a></td>
                                </tr>                               
                            }
                                                     
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
        <div class="row">
            <div class="col-md-6">
             
            </div>
            <div class="col-md-6 pl-5">
                <div class="row justify-content-end mx-2">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase text-center">Tổng Cộng</h3>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">Số tiền:</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">@Model.Sum(p => p.ThanhTien).ToString("#,##0.000")₫</strong>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">Phí:</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">Miễn phí vận chuyển trong nước</strong>
                            </div>
                        </div>
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Tổng tiền:</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">@Model.Sum(p => p.ThanhTien).ToString("#,##0.000")₫</strong>
                            </div>
                        </div>

                        <div class="row mb-3 text-center">
                            <div class="col-md-12">
                                <a  class="btn btn-black btn-lg py-3 btn-block"  asp-action="Checkout">Đặt Hàng</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>